[package]
name = "map_parser"
version = "0.1.0"
authors = ["Ghabriel <ghabriel.nunes@gmail.com>"]
edition = "2021"

[dependencies]
regex = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6.0"
